### ISSUE TITLE
Backend. Добавить аннотацию @CrossOrigin во все контроллеры

### ISSUE THREAD

**Issue by MikeKoms** [kartollika/Movies-Service#52]
Срочная задача!

**Comment by naatyzhvadim** [comment]
@MikeKoms а почему тут bug?

**Comment by MikeKoms** [comment]
Потому что отсутствие этой аннотации порождало баг :)

**Comment by MikeKoms** [comment]
А вишлист - это улучшение, потому что без этого метода все работает. Но с ним можно фичу хорошую реализовать.

**Comment by naatyzhvadim** [comment]
А все понял) Я неправильно понял метку bug. Думал это означает, что сам коммит содержит ошибку)
